/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/helper/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary Brand Colors
        primary: {
          50:  '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        // Secondary (Slate)
        secondary: {
          50:  '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
          950: '#020617',
        },
        // Accent (Emerald)
        accent: {
          50:  '#ECFDF5',
          100: '#D1FAE5',
          200: '#A7F3D0',
          400: '#34D399',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
        },
        // Surface
        surface: {
          light: '#F8FAFC',
          dark:  '#0F172A',
        },
      },
      fontFamily: {
        sans:    ['var(--font-inter)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-jakarta)', 'system-ui', 'sans-serif'],
        mono:    ['var(--font-geist-mono)', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '88': '22rem',
        '100': '25rem',
        '112': '28rem',
        '128': '32rem',
      },
      maxWidth: {
        'reading': '768px',
        '8xl': '88rem',
        '9xl': '96rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      boxShadow: {
        'card':      '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)',
        'card-hover':'0 10px 40px -10px rgb(0 0 0 / 0.15), 0 4px 16px -4px rgb(0 0 0 / 0.1)',
        'card-dark': '0 1px 3px 0 rgb(0 0 0 / 0.3)',
        'card-dark-hover': '0 10px 40px -10px rgb(0 0 0 / 0.5)',
        'nav':       '0 1px 0 0 rgb(0 0 0 / 0.06)',
        'dropdown':  '0 4px 24px -4px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.05)',
        'glow-blue': '0 0 20px rgb(37 99 235 / 0.25)',
      },
      backgroundImage: {
        'gradient-hero':       'linear-gradient(to bottom, transparent 0%, rgb(15 23 42 / 0.6) 50%, rgb(15 23 42 / 0.95) 100%)',
        'gradient-card':       'linear-gradient(to bottom, transparent 40%, rgb(15 23 42 / 0.9) 100%)',
        'gradient-primary':    'linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)',
        'gradient-newsletter': 'linear-gradient(135deg, #1E40AF 0%, #2563EB 50%, #059669 100%)',
        'noise':               "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")",
      },
      animation: {
        'fade-in':      'fadeIn 0.4s ease-out',
        'slide-up':     'slideUp 0.4s ease-out',
        'slide-down':   'slideDown 0.3s ease-out',
        'scale-in':     'scaleIn 0.2s ease-out',
        'shimmer':      'shimmer 1.5s infinite',
        'progress':     'progressGrow 0.3s ease-out',
        'bounce-soft':  'bounceSoft 0.6s ease-out',
        'ticker':       'ticker 20s linear infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' },                      to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:    { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer:      { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        bounceSoft:   { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        ticker:       { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body':          theme('colors.secondary.700'),
            '--tw-prose-headings':      theme('colors.secondary.900'),
            '--tw-prose-lead':          theme('colors.secondary.600'),
            '--tw-prose-links':         theme('colors.primary.600'),
            '--tw-prose-bold':          theme('colors.secondary.900'),
            '--tw-prose-counters':      theme('colors.secondary.500'),
            '--tw-prose-bullets':       theme('colors.secondary.400'),
            '--tw-prose-hr':            theme('colors.secondary.200'),
            '--tw-prose-quotes':        theme('colors.secondary.900'),
            '--tw-prose-quote-borders': theme('colors.primary.500'),
            '--tw-prose-captions':      theme('colors.secondary.500'),
            '--tw-prose-code':          theme('colors.primary.700'),
            '--tw-prose-pre-code':      theme('colors.secondary.100'),
            '--tw-prose-pre-bg':        theme('colors.secondary.800'),
            '--tw-prose-th-borders':    theme('colors.secondary.300'),
            '--tw-prose-td-borders':    theme('colors.secondary.200'),
            // Dark mode
            '--tw-prose-invert-body':         theme('colors.secondary.300'),
            '--tw-prose-invert-headings':     theme('colors.white'),
            '--tw-prose-invert-lead':         theme('colors.secondary.400'),
            '--tw-prose-invert-links':        theme('colors.primary.400'),
            '--tw-prose-invert-bold':         theme('colors.white'),
            '--tw-prose-invert-counters':     theme('colors.secondary.400'),
            '--tw-prose-invert-bullets':      theme('colors.secondary.500'),
            '--tw-prose-invert-hr':           theme('colors.secondary.700'),
            '--tw-prose-invert-quotes':       theme('colors.secondary.100'),
            '--tw-prose-invert-quote-borders':theme('colors.primary.500'),
            '--tw-prose-invert-captions':     theme('colors.secondary.400'),
            '--tw-prose-invert-code':         theme('colors.primary.300'),
            '--tw-prose-invert-pre-code':     theme('colors.secondary.300'),
            '--tw-prose-invert-pre-bg':       theme('colors.secondary.900'),
            '--tw-prose-invert-th-borders':   theme('colors.secondary.600'),
            '--tw-prose-invert-td-borders':   theme('colors.secondary.700'),
            maxWidth: 'none',
            fontSize: '1.0625rem',
            lineHeight: '1.8',
            p: { marginBottom: '1.5em', marginTop: '0' },
            h2: { fontSize: '1.5rem', fontWeight: '700', marginTop: '2.5em', marginBottom: '0.75em', fontFamily: theme('fontFamily.heading').join(', '), letterSpacing: '-0.01em' },
            h3: { fontSize: '1.25rem', fontWeight: '600', marginTop: '2em', marginBottom: '0.5em', fontFamily: theme('fontFamily.heading').join(', ') },
            h4: { fontSize: '1.1rem', fontWeight: '600', marginTop: '1.5em', marginBottom: '0.5em' },
            'a': { color: theme('colors.primary.600'), fontWeight: '500', textDecoration: 'underline', textDecorationColor: 'transparent', textUnderlineOffset: '2px', transition: 'text-decoration-color 200ms', '&:hover': { textDecorationColor: theme('colors.primary.600') } },
            'blockquote': { borderLeftWidth: '4px', borderLeftColor: theme('colors.primary.500'), backgroundColor: theme('colors.primary.50'), borderRadius: '0 0.5rem 0.5rem 0', padding: '1rem 1.5rem', fontStyle: 'normal', fontWeight: '500' },
            'code': { backgroundColor: theme('colors.secondary.100'), padding: '0.15em 0.4em', borderRadius: '0.25rem', fontSize: '0.875em', fontWeight: '500', '&::before': { content: '""' }, '&::after': { content: '""' } },
          },
        },
        invert: {
          css: {
            'blockquote': { backgroundColor: theme('colors.secondary.800') },
            'code': { backgroundColor: theme('colors.secondary.700') },
          },
        },
      }),
    },
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
  ],
};
